# Groq - API principale (gratuit, ultra rapide, Llama 3)
groq.key=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

# OpenRouter - Fallback
openrouter.key=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

# Grok - Fallback secondaire
grok.key=xai-tpH08L3WjMLBC1TpaF7sVSPQdnNQnJx3PGOqyvsc3ynckyPo6Uxk1jzUr0K7jXyai0sa8JOX3VE4LavB

# YouTube API - Pour les suggestions de videos
youtube.key=AIzaSyBQhfmi1stmbP-0d5y0-FO0ReNYq4NcM44

# Cohere - Backup supplementaire
cohere.key=wGzmEH7hMtYTCH62sgN6Wg4LuYT7pURii4EGXq5t