package planification.controllers;

import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import planification.services.AIService;

import java.net.URL;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Offboarding controller — generates a structured departure checklist.
 * AI enhancement: "🤖 Enrichir avec l'IA" button appends extra role-specific
 * and departure-reason-specific tasks generated by Groq.
 */
public class OffboardingController implements Initializable {

    // ── FXML nodes ────────────────────────────────────────────────────────
    @FXML private ComboBox<String> employeeCombo;
    @FXML private ComboBox<String> reasonCombo;
    @FXML private DatePicker       departureDatePicker;
    @FXML private Button           generateBtn;
    @FXML private HBox             statsRow;
    @FXML private VBox             taskPanel;
    @FXML private VBox             welcomeCard;
    @FXML private VBox             autoActionsCard;

    // ── State ─────────────────────────────────────────────────────────────
    private final List<TaskItem> currentTasks = new ArrayList<>();
    private final AIService      aiService    = new AIService();

    private String lastEmployee;
    private String lastReason;

    // ── Mock employee data {dept, email, role} ───────────────────────────
    private static final Map<String, String[]> EMPLOYEES = new LinkedHashMap<>();
    static {
        EMPLOYEES.put("Alice Martin",    new String[]{"Ingénierie", "alice.martin@humania.com",   "Développeuse Senior"});
        EMPLOYEES.put("Karim Bouzidi",   new String[]{"Marketing",  "karim.bouzidi@humania.com",  "Chef de projet"});
        EMPLOYEES.put("Sofia Trabelsi",  new String[]{"RH",         "sofia.trabelsi@humania.com", "Responsable RH"});
        EMPLOYEES.put("Lucas Bernard",   new String[]{"Finance",    "lucas.bernard@humania.com",  "Analyste financier"});
        EMPLOYEES.put("Yasmine Chouari", new String[]{"Ventes",     "yasmine.chouari@humania.com","Commerciale"});
        EMPLOYEES.put("Mohamed Haddad",  new String[]{"Ingénierie", "m.haddad@humania.com",       "DevOps Engineer"});
    }

    private static final String[] REASONS =
            {"Démission", "Fin de contrat", "Licenciement", "Retraite", "Rupture conventionnelle", "Mutation"};

    private static final List<String[]> COMMON_TASKS = List.of(
            new String[]{"📋", "Lettre de démission / notification officielle reçue", "Administratif", "30"},
            new String[]{"🗓", "Entretien de départ planifié",                         "RH",            "14"},
            new String[]{"📝", "Entretien de départ effectué",                         "RH",            "7"},
            new String[]{"🔄", "Plan de transfert de connaissances",                   "Opérationnel",  "14"},
            new String[]{"👥", "Transmission des responsabilités au remplaçant",       "Opérationnel",  "5"},
            new String[]{"📂", "Archivage et transfert des fichiers de travail",       "IT",            "3"},
            new String[]{"🖥",  "Restitution du matériel informatique",                 "Équipement",    "0"},
            new String[]{"🪪", "Restitution du badge d'accès",                         "Accès",         "0"},
            new String[]{"🔐", "Révocation de tous les accès informatiques",           "IT",            "0"},
            new String[]{"📧", "Désactivation du compte email",                        "IT",            "0"},
            new String[]{"🏥", "Clôture de l'affiliation mutuelle",                    "Administratif", "0"},
            new String[]{"💰", "Solde de tout compte préparé",                         "Finance",       "0"},
            new String[]{"📄", "Certificat de travail rédigé",                         "RH",            "0"},
            new String[]{"⭐", "Lettre de recommandation (si demandée)",               "RH",            "0"}
    );

    private static final Map<String, List<String[]>> REASON_TASKS = new HashMap<>();
    static {
        REASON_TASKS.put("Retraite", List.of(
                new String[]{"🎂", "Organisation de l'événement de départ",     "Intégration",  "7"},
                new String[]{"🏆", "Cérémonie de remise de cadeau",             "Intégration",  "0"},
                new String[]{"📸", "Photo souvenir avec l'équipe",              "Intégration",  "0"}
        ));
        REASON_TASKS.put("Mutation", List.of(
                new String[]{"🔀", "Coordination avec le site d'accueil",       "Opérationnel", "14"},
                new String[]{"📦", "Transfert du dossier RH au nouveau site",   "RH",           "5"},
                new String[]{"🪪", "Création badge nouveau site",               "Accès",        "0"}
        ));
        REASON_TASKS.put("Licenciement", List.of(
                new String[]{"⚖️", "Respect du délai de préavis légal",         "Administratif","30"},
                new String[]{"📜", "Remise des documents légaux obligatoires",  "Administratif","0"},
                new String[]{"💼", "Contact avec l'accompagnement emploi",      "RH",           "0"}
        ));
    }

    // ─────────────────────────────────────────────────────────────────────
    @Override
    public void initialize(URL location, ResourceBundle resources) {
        employeeCombo.getItems().addAll(EMPLOYEES.keySet());
        reasonCombo.getItems().addAll(REASONS);
        departureDatePicker.setValue(LocalDate.now().plusDays(30));
        showEmptyState();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Generate (unchanged logic)
    // ─────────────────────────────────────────────────────────────────────
    @FXML
    private void handleGenerate() {
        String employee = employeeCombo.getValue();
        String reason   = reasonCombo.getValue();
        LocalDate date  = departureDatePicker.getValue();

        if (employee == null || employee.isBlank()) {
            showAlert("Champ requis", "Veuillez sélectionner un employé.");
            return;
        }
        if (reason == null || reason.isBlank()) {
            showAlert("Champ requis", "Veuillez sélectionner le motif de départ.");
            return;
        }
        if (date == null) date = LocalDate.now().plusDays(30);

        lastEmployee = employee;
        lastReason   = reason;

        buildTasks(reason);
        renderTaskPanel();
        renderStats();
        renderEmployeeInfo(employee, reason, date);
        renderAutoActions(employee, reason);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Task generation (unchanged)
    // ─────────────────────────────────────────────────────────────────────
    private void buildTasks(String reason) {
        currentTasks.clear();
        for (String[] t : COMMON_TASKS)
            currentTasks.add(new TaskItem(t[0], t[1], t[2], Integer.parseInt(t[3])));
        List<String[]> extras = REASON_TASKS.getOrDefault(reason, List.of());
        for (String[] t : extras)
            currentTasks.add(new TaskItem(t[0], t[1], t[2], Integer.parseInt(t[3])));
        currentTasks.sort(Comparator.comparingInt((TaskItem t) -> t.dayOffset).reversed());
    }

    // ─────────────────────────────────────────────────────────────────────
    // AI ENHANCE — called when user clicks "🤖 Enrichir avec l'IA"
    // ─────────────────────────────────────────────────────────────────────
    private void handleAiEnhance(Button aiBtn, Label aiStatusLabel) {
        if (lastEmployee == null || lastReason == null) return;

        String[] info = EMPLOYEES.getOrDefault(lastEmployee,
                new String[]{"—", "", "Collaborateur"});
        String role = info[2];
        String dept = info[0];

        aiBtn.setDisable(true);
        aiBtn.setText("⏳ Génération en cours…");
        aiStatusLabel.setVisible(false);

        final String empName   = lastEmployee;
        final String empRole   = role;
        final String empDept   = dept;
        final String empReason = lastReason;

        Thread thread = new Thread(() -> {
            List<AIService.AiTask> aiTasks =
                    aiService.generateOffboardingTasks(empName, empRole, empDept, empReason);

            Platform.runLater(() -> {
                if (aiTasks.isEmpty()) {
                    aiStatusLabel.setText("⚠️ Aucune tâche générée. Vérifiez votre connexion.");
                    aiStatusLabel.setVisible(true);
                } else {
                    Set<String> existingLabels = new HashSet<>();
                    currentTasks.forEach(t -> existingLabels.add(t.label.toLowerCase()));

                    int added = 0;
                    for (AIService.AiTask t : aiTasks) {
                        if (!existingLabels.contains(t.label.toLowerCase())) {
                            currentTasks.add(new TaskItem(t.icon, t.label, t.category, t.dayOffset, true));
                            added++;
                        }
                    }
                    // Re-sort descending (offboarding: furthest from departure first)
                    currentTasks.sort(Comparator.comparingInt((TaskItem t) -> t.dayOffset).reversed());

                    renderTaskPanel();
                    renderStats();

                    aiStatusLabel.setText("✅ " + added + " tâche(s) IA ajoutée(s) !");
                    aiStatusLabel.setVisible(true);
                }

                aiBtn.setDisable(false);
                aiBtn.setText("🤖 Enrichir avec l'IA");
            });
        });
        thread.setDaemon(true);
        thread.start();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Rendering — task panel (unchanged logic, added AI row highlight)
    // ─────────────────────────────────────────────────────────────────────
    private void renderTaskPanel() {
        taskPanel.getChildren().clear();

        HBox header = new HBox();
        header.setAlignment(Pos.CENTER_LEFT);
        header.setPadding(new Insets(20, 20, 16, 20));
        header.setStyle("-fx-border-color: transparent transparent #f1f5f9 transparent; -fx-border-width: 0 0 1 0;");

        Label title = new Label("📋  Checklist de départ");
        title.setStyle("-fx-font-size: 16px; -fx-font-weight: bold; -fx-text-fill: #1e293b;");
        Region spacer = new Region(); HBox.setHgrow(spacer, Priority.ALWAYS);

        long done = currentTasks.stream().filter(t -> t.done).count();
        Label progress = new Label(done + " / " + currentTasks.size() + " complétées");
        progress.setStyle("-fx-font-size: 12px; -fx-text-fill: #64748b;");

        header.getChildren().addAll(title, spacer, progress);
        taskPanel.getChildren().add(header);

        double pct = currentTasks.isEmpty() ? 0 : (double) done / currentTasks.size();
        ProgressBar progressBar = new ProgressBar(pct);
        progressBar.setMaxWidth(Double.MAX_VALUE);
        progressBar.setPrefHeight(8);
        progressBar.setStyle(pct >= 1.0 ? "-fx-accent: #16a34a;" : "-fx-accent: #ef4444;");
        VBox.setMargin(progressBar, new Insets(0, 20, 16, 20));
        taskPanel.getChildren().add(progressBar);

        Map<String, List<TaskItem>> byCategory = new LinkedHashMap<>();
        for (TaskItem t : currentTasks) byCategory.computeIfAbsent(t.category, k -> new ArrayList<>()).add(t);

        for (Map.Entry<String, List<TaskItem>> entry : byCategory.entrySet()) {
            Label catLabel = new Label(entry.getKey().toUpperCase());
            catLabel.setStyle("-fx-font-size: 10px; -fx-font-weight: bold; -fx-text-fill: #94a3b8; " +
                    "-fx-padding: 10 20 6 20;");
            taskPanel.getChildren().add(catLabel);

            for (TaskItem task : entry.getValue()) {
                HBox row = buildTaskRow(task);
                taskPanel.getChildren().add(row);
                Region sep = new Region();
                sep.setStyle("-fx-background-color: #f8fafc;");
                sep.setPrefHeight(1);
                taskPanel.getChildren().add(sep);
            }
        }
        taskPanel.getChildren().add(new Region());
    }

    private HBox buildTaskRow(TaskItem task) {
        HBox row = new HBox(14);
        row.setAlignment(Pos.CENTER_LEFT);
        row.setPadding(new Insets(10, 20, 10, 20));
        String baseStyle = task.aiGenerated ? "-fx-background-color: #fff5f0; -fx-cursor: hand;" : "-fx-cursor: hand;";
        row.setStyle(baseStyle);

        StackPane checkBox = buildCheckCircle(task.done, "#ef4444");
        Label icon = new Label(task.icon);
        icon.setStyle("-fx-font-size: 16px;");

        VBox labelBox = new VBox(2);
        Label name = new Label(task.label);
        name.setStyle("-fx-font-size: 13px; -fx-font-weight: bold; -fx-text-fill: "
                + (task.done ? "#94a3b8" : "#1e293b") + ";");
        if (task.done) name.setStyle(name.getStyle() + " -fx-strikethrough: true;");
        String dayLabel = task.dayOffset == 0 ? "Jour J (départ)" : "J-" + task.dayOffset;
        String subText  = dayLabel + "  ·  " + task.category;
        if (task.aiGenerated) subText += "  ·  🤖 IA";
        Label sub = new Label(subText);
        sub.setStyle("-fx-font-size: 11px; -fx-text-fill: #94a3b8;");
        labelBox.getChildren().addAll(name, sub);
        HBox.setHgrow(labelBox, Priority.ALWAYS);

        String badgeBg = task.dayOffset == 0 ? "#fee2e2" : task.dayOffset <= 5 ? "#fef3c7" : "#f1f5f9";
        String badgeFg = task.dayOffset == 0 ? "#dc2626" : task.dayOffset <= 5 ? "#f59e0b" : "#64748b";
        Label dayBadge = makeBadge(dayLabel, badgeBg, badgeFg);

        row.getChildren().addAll(checkBox, icon, labelBox, dayBadge);

        row.setOnMouseClicked(e -> {
            task.done = !task.done;
            renderTaskPanel();
            renderStats();
        });
        row.setOnMouseEntered(e -> row.setStyle("-fx-background-color: #fff5f5; -fx-cursor: hand;"));
        row.setOnMouseExited(e -> row.setStyle(baseStyle));

        return row;
    }

    private StackPane buildCheckCircle(boolean done, String color) {
        StackPane sp = new StackPane();
        Circle c = new Circle(11);
        c.setFill(done ? Color.web(color) : Color.TRANSPARENT);
        c.setStroke(Color.web(done ? color : "#cbd5e1"));
        c.setStrokeWidth(2);
        Label check = new Label(done ? "✓" : "");
        check.setStyle("-fx-text-fill: white; -fx-font-size: 11px; -fx-font-weight: bold;");
        sp.getChildren().addAll(c, check);
        return sp;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Rendering — stats (added AI counter)
    // ─────────────────────────────────────────────────────────────────────
    private void renderStats() {
        statsRow.getChildren().clear();
        long done    = currentTasks.stream().filter(t -> t.done).count();
        long total   = currentTasks.size();
        long urgent  = currentTasks.stream().filter(t -> t.dayOffset == 0 && !t.done).count();
        long aiCount = currentTasks.stream().filter(t -> t.aiGenerated).count();

        statsRow.getChildren().addAll(
                statCard("📋", String.valueOf(total),   "Tâches totales",  "#475569", "#f1f5f9"),
                statCard("✅", String.valueOf(done),    "Complétées",      "#16a34a", "#dcfce7"),
                statCard("🚨", String.valueOf(urgent),  "Urgentes (J)",    "#dc2626", "#fee2e2"),
                statCard("🤖", String.valueOf(aiCount), "Tâches IA",       "#f59e0b", "#fef3c7")
        );
    }

    private VBox statCard(String icon, String value, String label, String fg, String bg) {
        VBox card = new VBox(4);
        card.setAlignment(Pos.CENTER_LEFT);
        card.setPadding(new Insets(16, 20, 16, 20));
        card.setStyle("-fx-background-color: white; -fx-background-radius: 10; " +
                "-fx-border-color: #e2e8f0; -fx-border-radius: 10; " +
                "-fx-effect: dropshadow(gaussian, rgba(0,0,0,0.04), 6, 0, 0, 1);");
        card.setPrefWidth(180);

        Label iconLbl  = new Label(icon);  iconLbl.setStyle("-fx-font-size: 18px;");
        Label valueLbl = new Label(value); valueLbl.setStyle("-fx-font-size: 28px; -fx-font-weight: bold; -fx-text-fill: " + fg + ";");
        Label labelLbl = new Label(label); labelLbl.setStyle("-fx-font-size: 12px; -fx-text-fill: #64748b;");

        card.getChildren().addAll(iconLbl, valueLbl, labelLbl);
        return card;
    }

    // ─────────────────────────────────────────────────────────────────────
    // Rendering — employee info card (unchanged)
    // ─────────────────────────────────────────────────────────────────────
    private void renderEmployeeInfo(String name, String reason, LocalDate date) {
        welcomeCard.getChildren().clear();

        Label title = new Label("👤  Informations employé");
        title.setStyle("-fx-font-size: 14px; -fx-font-weight: bold; -fx-text-fill: #1e293b;");
        welcomeCard.getChildren().add(title);

        StackPane avatar = new StackPane();
        Circle bg = new Circle(30);
        bg.setFill(Color.web("#fee2e2"));
        Label initials = new Label(getInitials(name));
        initials.setStyle("-fx-font-size: 18px; -fx-font-weight: bold; -fx-text-fill: #dc2626;");
        avatar.getChildren().addAll(bg, initials);

        String[] info = EMPLOYEES.getOrDefault(name, new String[]{"—", "", "Collaborateur"});
        Label nameLbl = new Label(name);
        nameLbl.setStyle("-fx-font-size: 15px; -fx-font-weight: bold; -fx-text-fill: #1e293b;");
        Label roleLbl = new Label(info[2]);
        roleLbl.setStyle("-fx-font-size: 12px; -fx-text-fill: #ef4444;");

        HBox nameRow = new HBox(12, avatar, new VBox(2, nameLbl, roleLbl));
        nameRow.setAlignment(Pos.CENTER_LEFT);
        welcomeCard.getChildren().add(nameRow);

        Region div = new Region(); div.setPrefHeight(1);
        div.setStyle("-fx-background-color: #f1f5f9;");
        welcomeCard.getChildren().add(div);

        String email = info[1].isEmpty() ? name.toLowerCase().replace(" ", ".") + "@humania.com" : info[1];
        welcomeCard.getChildren().addAll(
                infoRow("🏢", "Département",     info[0]),
                infoRow("📧", "Email",           email),
                infoRow("📅", "Date de départ",  date.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"))),
                infoRow("📌", "Motif",           reason),
                infoRow("📋", "Tâches générées", currentTasks.size() + " étapes")
        );

        Label statusBadge = makeBadge("● Offboarding en cours", "#fee2e2", "#dc2626");
        welcomeCard.getChildren().add(statusBadge);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Rendering — auto-actions card  ← AI button added here
    // ─────────────────────────────────────────────────────────────────────
    private void renderAutoActions(String employee, String reason) {
        autoActionsCard.getChildren().clear();

        Label title = new Label("⚙️  Actions automatiques");
        title.setStyle("-fx-font-size: 14px; -fx-font-weight: bold; -fx-text-fill: #1e293b;");
        autoActionsCard.getChildren().add(title);

        Label sub = new Label("Déclenchées automatiquement à la génération du parcours");
        sub.setStyle("-fx-font-size: 11px; -fx-text-fill: #94a3b8; -fx-wrap-text: true;");
        autoActionsCard.getChildren().add(sub);

        String email = EMPLOYEES.getOrDefault(employee,
                new String[]{"", employee.toLowerCase().replace(" ", ".") + "@humania.com", ""})[1];
        if (email.isBlank()) email = employee.toLowerCase().replace(" ", ".") + "@humania.com";
        String login = email.split("@")[0];

        List<String[]> actions = new ArrayList<>();
        actions.add(new String[]{"📧", "Email de notification envoyé au manager",    "Copie RH en CC",                    "#fee2e2", "#dc2626"});
        actions.add(new String[]{"🗓", "Entretien de départ planifié",               "Calendrier mis à jour",              "#fef3c7", "#f59e0b"});
        actions.add(new String[]{"🔐", "Alerte IT — révocation accès planifiée",     "Le J de départ : " + login,          "#f1f5f9", "#475569"});
        actions.add(new String[]{"📂", "Dossier de départ créé",                     "Archivage automatique RH",           "#ede9fe", "#667eea"});
        actions.add(new String[]{"💰", "Service paie notifié",                       "Solde de tout compte à préparer",    "#dcfce7", "#16a34a"});
        if (reason.equals("Retraite")) {
            actions.add(new String[]{"🎉", "Invitation départ en retraite envoyée", "À toute l'équipe",                   "#fef3c7", "#f59e0b"});
        }
        actions.add(new String[]{"📄", "Génération documents légaux déclenchée",     "Certificat de travail + attestation","#e0f2fe", "#0ea5e9"});

        for (String[] a : actions) {
            HBox row = new HBox(10);
            row.setAlignment(Pos.CENTER_LEFT);
            row.setPadding(new Insets(8, 12, 8, 12));
            row.setStyle("-fx-background-color: " + a[3] + "; -fx-background-radius: 8;");
            Label ic = new Label(a[0]); ic.setStyle("-fx-font-size: 15px;");
            VBox txt = new VBox(1);
            Label lbl = new Label(a[1]);
            lbl.setStyle("-fx-font-size: 12px; -fx-font-weight: bold; -fx-text-fill: " + a[4] + ";");
            Label det = new Label(a[2]);
            det.setStyle("-fx-font-size: 11px; -fx-text-fill: #64748b;");
            txt.getChildren().addAll(lbl, det);
            Label ok = new Label("✓");
            ok.setStyle("-fx-font-size: 12px; -fx-font-weight: bold; -fx-text-fill: " + a[4] + ";");
            Region sp = new Region(); HBox.setHgrow(sp, Priority.ALWAYS);
            row.getChildren().addAll(ic, txt, sp, ok);
            autoActionsCard.getChildren().add(row);
        }

        // ── Existing buttons ──────────────────────────────────────────────
        Button markAll = new Button("✅  Tout marquer complété");
        markAll.setStyle("-fx-background-color: #ef4444; -fx-text-fill: white; -fx-font-weight: bold;" +
                " -fx-font-size: 12px; -fx-padding: 8 16; -fx-background-radius: 8; -fx-cursor: hand;");
        markAll.setMaxWidth(Double.MAX_VALUE);
        markAll.setOnAction(e -> {
            currentTasks.forEach(t -> t.done = true);
            renderTaskPanel();
            renderStats();
        });

        Button resetBtn = new Button("↺  Réinitialiser");
        resetBtn.setStyle("-fx-background-color: white; -fx-text-fill: #64748b; -fx-font-size: 12px;" +
                " -fx-padding: 8 16; -fx-background-radius: 8; -fx-border-color: #e2e8f0;" +
                " -fx-border-radius: 8; -fx-cursor: hand;");
        resetBtn.setMaxWidth(Double.MAX_VALUE);
        resetBtn.setOnAction(e -> {
            currentTasks.forEach(t -> t.done = false);
            renderTaskPanel();
            renderStats();
        });

        // ── 🤖 AI button + status label ───────────────────────────────────
        Region divider = new Region();
        divider.setPrefHeight(1);
        divider.setStyle("-fx-background-color: #e2e8f0;");
        VBox.setMargin(divider, new Insets(6, 0, 6, 0));

        Button aiBtn = new Button("🤖 Enrichir avec l'IA");
        aiBtn.setStyle(
                "-fx-background-color: linear-gradient(to right, #ef4444, #f97316);" +
                        "-fx-text-fill: white; -fx-font-weight: bold; -fx-font-size: 12px;" +
                        "-fx-padding: 9 16; -fx-background-radius: 8; -fx-cursor: hand;");
        aiBtn.setMaxWidth(Double.MAX_VALUE);

        Label aiStatusLabel = new Label("");
        aiStatusLabel.setVisible(false);
        aiStatusLabel.setStyle("-fx-font-size: 11px; -fx-text-fill: #ef4444; -fx-font-style: italic;");
        aiStatusLabel.setWrapText(true);

        aiBtn.setOnAction(e -> handleAiEnhance(aiBtn, aiStatusLabel));

        autoActionsCard.getChildren().addAll(markAll, resetBtn, divider, aiBtn, aiStatusLabel);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Empty state (unchanged)
    // ─────────────────────────────────────────────────────────────────────
    private void showEmptyState() {
        taskPanel.getChildren().clear();
        VBox empty = new VBox(12);
        empty.setAlignment(Pos.CENTER);
        empty.setPadding(new Insets(60));
        Label ico = new Label("👋");
        ico.setStyle("-fx-font-size: 48px;");
        Label msg = new Label("Sélectionnez un employé et le motif de départ,\npuis cliquez sur \"Générer le parcours\".");
        msg.setStyle("-fx-font-size: 14px; -fx-text-fill: #94a3b8; -fx-text-alignment: center; -fx-alignment: center;");
        msg.setWrapText(true);
        empty.getChildren().addAll(ico, msg);
        taskPanel.getChildren().add(empty);
    }

    // ─────────────────────────────────────────────────────────────────────
    // Helpers (unchanged)
    // ─────────────────────────────────────────────────────────────────────
    private HBox infoRow(String icon, String key, String value) {
        HBox row = new HBox(8);
        row.setAlignment(Pos.CENTER_LEFT);
        row.setPadding(new Insets(3, 0, 3, 0));
        Label ic = new Label(icon); ic.setStyle("-fx-font-size: 13px;");
        Label k  = new Label(key + " :"); k.setStyle("-fx-font-size: 12px; -fx-text-fill: #94a3b8; -fx-min-width: 110;");
        Label v  = new Label(value); v.setStyle("-fx-font-size: 12px; -fx-font-weight: bold; -fx-text-fill: #475569;");
        row.getChildren().addAll(ic, k, v);
        return row;
    }

    private Label makeBadge(String text, String bg, String fg) {
        Label l = new Label(text);
        l.setStyle("-fx-background-color: " + bg + "; -fx-text-fill: " + fg + "; " +
                "-fx-padding: 4 10; -fx-background-radius: 20; -fx-font-size: 11px; -fx-font-weight: bold;");
        return l;
    }

    private String getInitials(String name) {
        String[] parts = name.trim().split("\\s+");
        if (parts.length >= 2) return String.valueOf(parts[0].charAt(0)) + parts[1].charAt(0);
        return name.substring(0, Math.min(2, name.length())).toUpperCase();
    }

    private void showAlert(String title, String msg) {
        Alert a = new Alert(Alert.AlertType.WARNING);
        a.setTitle(title); a.setHeaderText(null); a.setContentText(msg); a.showAndWait();
    }

    // ─────────────────────────────────────────────────────────────────────
    // Inner model — added aiGenerated flag
    // ─────────────────────────────────────────────────────────────────────
    private static class TaskItem {
        final String icon, label, category;
        final int    dayOffset;
        boolean      done        = false;
        boolean      aiGenerated = false;

        TaskItem(String icon, String label, String category, int dayOffset) {
            this.icon      = icon;
            this.label     = label;
            this.category  = category;
            this.dayOffset = dayOffset;
        }

        TaskItem(String icon, String label, String category, int dayOffset, boolean aiGenerated) {
            this(icon, label, category, dayOffset);
            this.aiGenerated = aiGenerated;
        }
    }
}